import type { ApplicantProfile, FundingProgram } from "@/types/domain";

export type ScrapedFundingProgramme = FundingProgram & {
  id?: string;
  program_name?: string | null;
  program_slug?: string | null;
  parent_programme_name?: string | null;
  funder_name?: string | null;
  funder_slug?: string | null;
  country_code?: string | null;
  site_adapter?: string | null;
  page_type?: string | null;
  source_url?: string;
  sourceDomain?: string;
  sourceUrls?: string[];
  source_urls?: string[];
  source_page_title?: string | null;
  source_domain?: string | null;
  scraped_at?: string;
  last_scraped_at?: string;
  last_verified_at?: string | null;
  fundingLines?: string[];
  funding_lines?: string[];
  funding_type?: string | null;
  deadlineType?: string | null;
  deadline_type?: string | null;
  deadlineDate?: string | null;
  deadline_date?: string | null;
  geographyScope?: string | null;
  geography_scope?: string | null;
  provinces?: string[];
  municipalities?: string[];
  postalCodeRanges?: string[];
  postal_code_ranges?: string[];
  industries?: string[];
  useOfFunds?: string[];
  use_of_funds?: string[];
  businessStageEligibility?: string[];
  business_stage_eligibility?: string[];
  turnoverMin?: number | null;
  turnover_min?: number | null;
  turnoverMax?: number | null;
  turnover_max?: number | null;
  yearsInBusinessMin?: number | null;
  years_in_business_min?: number | null;
  yearsInBusinessMax?: number | null;
  years_in_business_max?: number | null;
  employeeMin?: number | null;
  employee_min?: number | null;
  employeeMax?: number | null;
  employee_max?: number | null;
  ticket_min?: number | string | null;
  ticket_max?: number | string | null;
  amountMin?: number;
  amountMax?: number;
  status?: FundingProgram["status"];
  sourceUrl?: string;
  sourceName?: string;
  title?: string;
  providerName?: string;
  fundingType?: FundingProgram["fundingType"];
  eligibilitySummary?: string;
  scrapeConfidence?: number;
  approvalStatus?: FundingProgram["approvalStatus"];
  lastScrapedAt?: string;
  createdAt?: string;
  updatedAt?: string;
  ownershipTargets?: string[];
  ownership_targets?: string[];
  entityTypesAllowed?: string[];
  entity_types_allowed?: string[];
  certificationsRequired?: string[];
  certifications_required?: string[];
  applicationChannel?: string | null;
  application_channel?: string | null;
  applicationUrl?: string | null;
  application_url?: string | null;
  contactEmail?: string | null;
  contact_email?: string | null;
  contactPhone?: string | null;
  contact_phone?: string | null;
  rawEligibilityData?: string | string[] | null;
  raw_eligibility_data?: string | string[] | null;
  raw_funding_offer_data?: string[] | Record<string, unknown> | null;
  raw_terms_data?: string[] | Record<string, unknown> | null;
  raw_documents_data?: string[] | Record<string, unknown> | null;
  raw_application_data?: string[] | Record<string, unknown> | null;
  evidence_by_field?: Record<string, unknown>;
  field_confidence?: Record<string, number>;
  parser_version?: string | null;
  needs_review?: boolean | null;
  validation_errors?: string[] | Record<string, unknown> | null;
  deleted_at?: string | null;
  relatedDocuments?: string[];
  related_documents?: string[];
  notes?: string[];
  ai_enriched?: boolean;
};

export interface BusinessProfile {
  userId?: string;
  country?: string;
  province?: string;
  municipality?: string;
  sectors: string[];
  stage?: ApplicantProfile["stage"] | string;
  ownershipTargets?: string[];
  useOfFunds?: string[];
  yearsOperating?: number;
  turnoverMin?: number;
  turnoverMax?: number;
  employeeCount?: number;
  requestedFundingMin?: number;
  requestedFundingMax?: number;
  preferredFundingTypes?: Array<FundingProgram["fundingType"]>;
  organizationType?: ApplicantProfile["organizationType"] | string;
}

export interface ProgrammeScoreBreakdown {
  qualityScore: number;
  matchScore: number;
  importanceScore: number;
  qualityReasons: string[];
  matchReasons: string[];
  reasonTags: string[];
  blockers: string[];
  scoreBand: "high" | "medium" | "low";
}

export type ScoredProgramme = ScrapedFundingProgramme & ProgrammeScoreBreakdown;
