"""Built-in funding site adapters for the current seed domains."""

from __future__ import annotations

from typing import List

from scraper.adapters.base import SiteAdapter
from scraper.adapters.nyda import NydaSiteAdapter
from scraper.adapters.nefcorp import NefcorpSiteAdapter


def _adapter(
    key: str,
    domain: str,
    *,
    default_seed_urls: List[str],
    allowed_path_prefixes: List[str] | None = None,
    include_url_terms: List[str] | None = None,
    exclude_url_terms: List[str] | None = None,
    discovery_terms: List[str] | None = None,
    content_selectors: List[str] | None = None,
    candidate_selectors: List[str] | None = None,
    parent_page_terms: List[str] | None = None,
    child_page_terms: List[str] | None = None,
    merge_aliases: dict[str, str] | None = None,
    playwright_required_by_default: bool = False,
    notes: List[str] | None = None,
) -> SiteAdapter:
    return SiteAdapter(
        key=key,
        domain=domain,
        allowed_path_prefixes=tuple(allowed_path_prefixes or ()),
        default_seed_urls=tuple(default_seed_urls),
        include_url_terms=tuple(include_url_terms or ()),
        exclude_url_terms=tuple(exclude_url_terms or ()),
        discovery_terms=tuple(discovery_terms or ()),
        content_selectors=tuple(content_selectors or ()),
        candidate_selectors=tuple(candidate_selectors or ()),
        parent_page_terms=tuple(parent_page_terms or ()),
        child_page_terms=tuple(child_page_terms or ()),
        merge_aliases=merge_aliases or {},
        playwright_required_by_default=playwright_required_by_default,
        notes=tuple(notes or ()),
    )


DEFAULT_SITE_ADAPTERS: List[SiteAdapter] = [
    _adapter(
        "sefa",
        "sedfa.org.za",
        default_seed_urls=["https://www.sedfa.org.za/products/direct-lending-products"],
        allowed_path_prefixes=["/products/", "/programmes/", "/funding/"],
        include_url_terms=["fund", "loan", "grant", "product", "program", "programme"],
        exclude_url_terms=["/news/", "/media/", "/press/", "/blog/"],
        discovery_terms=["fund", "loan", "grant", "apply", "programme"],
        content_selectors=["main", "article", ".content", ".programme-content"],
        candidate_selectors=["article", "section.card", "section", ".card", ".programme-card"],
        parent_page_terms=["products", "programmes"],
        child_page_terms=["direct lending", "product"],
        merge_aliases={"apply now": "", "overview": ""},
    ),
    _adapter(
        "idc",
        "idc.co.za",
        default_seed_urls=["https://www.idc.co.za/"],
        allowed_path_prefixes=["/funding-solutions/"],
        include_url_terms=["funding", "apply", "solution", "programme", "program", "tenders"],
        exclude_url_terms=["/press-releases/", "/news/", "/media/", "/publications/", "/press/"],
        discovery_terms=["funding", "apply", "financial", "solutions"],
        content_selectors=["main", "article", ".content", ".programme-content"],
        candidate_selectors=["article", "section.card", "section", ".card", ".news-item"],
        parent_page_terms=["funding solutions"],
        child_page_terms=["funding"],
        playwright_required_by_default=False,
        notes=["Exclude press-release style pages from the main programme queue."],
    ),
    NydaSiteAdapter.build(),
    _adapter(
        "dtic",
        "thedtic.gov.za",
        default_seed_urls=["https://www.thedtic.gov.za/"],
        allowed_path_prefixes=["/financial-assistance/", "/funding/", "/incentives/", "/programmes/"],
        include_url_terms=["fund", "grant", "loan", "incentive", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/", "/publications/"],
        discovery_terms=["funding", "incentive", "support"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card", ".tile"],
        parent_page_terms=["funding", "incentives"],
    ),
    NefcorpSiteAdapter.build(),
    _adapter(
        "dsbd",
        "dsbd.gov.za",
        default_seed_urls=["http://dsbd.gov.za/"],
        allowed_path_prefixes=["/funding/", "/programmes/", "/support/"],
        include_url_terms=["fund", "loan", "grant", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "programme"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
        parent_page_terms=["funding"],
    ),
    _adapter(
        "dbsa",
        "dbsa.org",
        default_seed_urls=["https://www.dbsa.org"],
        allowed_path_prefixes=["/projects-and-products/", "/funding/", "/finance/"],
        include_url_terms=["fund", "loan", "grant", "finance", "programme", "project"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "finance"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "gep",
        "gep.co.za",
        default_seed_urls=["https://www.gep.co.za/"],
        allowed_path_prefixes=["/funding/", "/products/", "/business-funding/"],
        include_url_terms=["fund", "loan", "grant", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "programme"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "tia",
        "tia.org.za",
        default_seed_urls=["https://www.tia.org.za/funding-instruments/"],
        allowed_path_prefixes=["/funding-instruments/"],
        include_url_terms=["fund", "instrument", "grant", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "instruments"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
        parent_page_terms=["funding instruments"],
    ),
    _adapter(
        "pic",
        "pic.gov.za",
        default_seed_urls=["https://www.pic.gov.za/"],
        allowed_path_prefixes=["/funding/", "/programmes/", "/investment/"],
        include_url_terms=["fund", "invest", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "investment"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "landbank",
        "landbank.co.za",
        default_seed_urls=["https://landbank.co.za/Pages/Home.aspx"],
        allowed_path_prefixes=["/pages/", "/products/", "/funding/", "/loan/"],
        include_url_terms=["loan", "fund", "grant", "finance", "apply", "product"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "loan", "finance"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "ithala",
        "ithala.co.za",
        default_seed_urls=["https://www.ithala.co.za/"],
        allowed_path_prefixes=["/business-loans/", "/funding/", "/products/"],
        include_url_terms=["loan", "fund", "finance", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "loan"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "lieda",
        "lieda.co.za",
        default_seed_urls=["https://www.lieda.co.za/"],
        allowed_path_prefixes=["/funding/", "/programmes/"],
        include_url_terms=["fund", "loan", "grant", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "programme"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "mega",
        "mega.gov.za",
        default_seed_urls=["https://mega.gov.za/"],
        allowed_path_prefixes=["/funding/", "/programmes/"],
        include_url_terms=["fund", "grant", "loan", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "programme"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "nwdc",
        "nwdc.co.za",
        default_seed_urls=["https://nwdc.co.za/"],
        allowed_path_prefixes=["/funding/", "/programmes/", "/business-support/"],
        include_url_terms=["fund", "loan", "grant", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "support"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
    _adapter(
        "nceda",
        "northern-cape.gov.za",
        default_seed_urls=["http://www.northern-cape.gov.za/dedat/index.php"],
        allowed_path_prefixes=["/dedat/", "/funding/", "/programmes/"],
        include_url_terms=["fund", "grant", "loan", "programme", "apply"],
        exclude_url_terms=["/news/", "/media/", "/press/"],
        discovery_terms=["funding", "programme"],
        content_selectors=["main", "article", ".content"],
        candidate_selectors=["article", "section.card", ".card"],
    ),
]
