begin;

alter table public.funding_programmes
  add column if not exists site_adapter text,
  add column if not exists page_type text,
  add column if not exists parent_programme_name text;

create table if not exists public.sub_funding_programmes (
  sub_program_id text primary key,
  parent_program_id text not null references public.funding_programmes (program_id) on delete cascade,
  parent_program_name text,
  sub_program_name text,
  funder_name text,
  site_adapter text,
  page_type text,
  source_url text not null,
  source_urls jsonb not null default '[]'::jsonb,
  source_domain text not null,
  source_page_title text,
  scraped_at timestamptz not null default now(),
  raw_eligibility_data jsonb,
  funding_type text not null default 'Unknown' check (funding_type in ('Grant', 'Loan', 'Equity', 'Guarantee', 'Hybrid', 'Other', 'Unknown')),
  funding_lines jsonb not null default '[]'::jsonb,
  ticket_min numeric,
  ticket_max numeric,
  currency text,
  program_budget_total numeric,
  deadline_type text not null default 'Unknown' check (deadline_type in ('FixedDate', 'Rolling', 'Open', 'Unknown')),
  deadline_date date,
  funding_speed_days_min integer,
  funding_speed_days_max integer,
  geography_scope text not null default 'Unknown' check (geography_scope in ('National', 'Province', 'Municipality', 'Local', 'International', 'Unknown')),
  provinces jsonb not null default '[]'::jsonb,
  municipalities jsonb not null default '[]'::jsonb,
  postal_code_ranges jsonb not null default '[]'::jsonb,
  industries jsonb not null default '[]'::jsonb,
  use_of_funds jsonb not null default '[]'::jsonb,
  business_stage_eligibility jsonb not null default '[]'::jsonb,
  turnover_min numeric,
  turnover_max numeric,
  years_in_business_min numeric,
  years_in_business_max numeric,
  employee_min integer,
  employee_max integer,
  ownership_targets jsonb not null default '[]'::jsonb,
  entity_types_allowed jsonb not null default '[]'::jsonb,
  certifications_required jsonb not null default '[]'::jsonb,
  security_required text not null default 'Unknown' check (security_required in ('Yes', 'No', 'Maybe', 'Unknown')),
  equity_required text not null default 'Unknown' check (equity_required in ('Yes', 'No', 'Maybe', 'Unknown')),
  payback_months_min integer,
  payback_months_max integer,
  interest_type text not null default 'Unknown' check (interest_type in ('Fixed', 'Prime-linked', 'Factor-rate', 'Unknown')),
  repayment_frequency text not null default 'Unknown' check (repayment_frequency in ('Weekly', 'Monthly', 'Variable', 'Unknown')),
  exclusions jsonb not null default '[]'::jsonb,
  required_documents jsonb not null default '[]'::jsonb,
  application_channel text not null default 'Unknown' check (application_channel in ('Online form', 'Email', 'Branch', 'Partner referral', 'Unknown')),
  application_url text,
  contact_email text,
  contact_phone text,
  raw_text_snippets jsonb not null default '{}'::jsonb,
  extraction_confidence jsonb not null default '{}'::jsonb,
  related_documents jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_sub_funding_programmes_parent_program_id on public.sub_funding_programmes (parent_program_id);
create index if not exists idx_sub_funding_programmes_sub_program_name on public.sub_funding_programmes (sub_program_name);
create index if not exists idx_sub_funding_programmes_funder_name on public.sub_funding_programmes (funder_name);
create index if not exists idx_sub_funding_programmes_source_domain on public.sub_funding_programmes (source_domain);

drop trigger if exists trg_sub_funding_programmes_updated_at on public.sub_funding_programmes;
create trigger trg_sub_funding_programmes_updated_at
before update on public.sub_funding_programmes
for each row
execute procedure public.set_updated_at();

alter table public.sub_funding_programmes enable row level security;

drop policy if exists "Public read sub funding programmes" on public.sub_funding_programmes;
create policy "Public read sub funding programmes"
on public.sub_funding_programmes
for select
using (true);

create or replace function public.ingest_funding_programmes(records jsonb, run_summary jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  rec jsonb;
  resolved_parent_program_id text;
  upserted_records integer := 0;
  upserted_sub_records integer := 0;
begin
  if coalesce(jsonb_typeof(records), '') <> 'array' then
    raise exception 'records must be a json array';
  end if;

  for rec in
    select value
    from jsonb_array_elements(records)
    where coalesce(nullif(value->>'page_type', ''), 'detail') <> 'sub-product'
  loop
    insert into public.funding_programmes (
      program_id,
      program_name,
      funder_name,
      site_adapter,
      page_type,
      parent_programme_name,
      source_url,
      source_urls,
      source_domain,
      source_page_title,
      scraped_at,
      raw_eligibility_data,
      funding_type,
      funding_lines,
      ticket_min,
      ticket_max,
      currency,
      program_budget_total,
      deadline_type,
      deadline_date,
      funding_speed_days_min,
      funding_speed_days_max,
      geography_scope,
      provinces,
      municipalities,
      postal_code_ranges,
      industries,
      use_of_funds,
      business_stage_eligibility,
      turnover_min,
      turnover_max,
      years_in_business_min,
      years_in_business_max,
      employee_min,
      employee_max,
      ownership_targets,
      entity_types_allowed,
      certifications_required,
      security_required,
      equity_required,
      payback_months_min,
      payback_months_max,
      interest_type,
      repayment_frequency,
      exclusions,
      required_documents,
      application_channel,
      application_url,
      contact_email,
      contact_phone,
      raw_text_snippets,
      extraction_confidence,
      related_documents,
      notes
    )
    values (
      coalesce(rec->>'program_id', gen_random_uuid()::text),
      nullif(rec->>'program_name', ''),
      nullif(rec->>'funder_name', ''),
      nullif(rec->>'site_adapter', ''),
      nullif(rec->>'page_type', ''),
      nullif(rec->>'parent_programme_name', ''),
      rec->>'source_url',
      coalesce(rec->'source_urls', '[]'::jsonb),
      rec->>'source_domain',
      nullif(rec->>'source_page_title', ''),
      coalesce((rec->>'scraped_at')::timestamptz, now()),
      case when rec ? 'raw_eligibility_data' then rec->'raw_eligibility_data' else null end,
      coalesce(nullif(rec->>'funding_type', ''), 'Unknown'),
      coalesce(rec->'funding_lines', '[]'::jsonb),
      nullif(rec->>'ticket_min', '')::numeric,
      nullif(rec->>'ticket_max', '')::numeric,
      nullif(rec->>'currency', ''),
      nullif(rec->>'program_budget_total', '')::numeric,
      coalesce(nullif(rec->>'deadline_type', ''), 'Unknown'),
      nullif(rec->>'deadline_date', '')::date,
      nullif(rec->>'funding_speed_days_min', '')::integer,
      nullif(rec->>'funding_speed_days_max', '')::integer,
      coalesce(nullif(rec->>'geography_scope', ''), 'Unknown'),
      coalesce(rec->'provinces', '[]'::jsonb),
      coalesce(rec->'municipalities', '[]'::jsonb),
      coalesce(rec->'postal_code_ranges', '[]'::jsonb),
      coalesce(rec->'industries', '[]'::jsonb),
      coalesce(rec->'use_of_funds', '[]'::jsonb),
      coalesce(rec->'business_stage_eligibility', '[]'::jsonb),
      nullif(rec->>'turnover_min', '')::numeric,
      nullif(rec->>'turnover_max', '')::numeric,
      nullif(rec->>'years_in_business_min', '')::numeric,
      nullif(rec->>'years_in_business_max', '')::numeric,
      nullif(rec->>'employee_min', '')::integer,
      nullif(rec->>'employee_max', '')::integer,
      coalesce(rec->'ownership_targets', '[]'::jsonb),
      coalesce(rec->'entity_types_allowed', '[]'::jsonb),
      coalesce(rec->'certifications_required', '[]'::jsonb),
      coalesce(nullif(rec->>'security_required', ''), 'Unknown'),
      coalesce(nullif(rec->>'equity_required', ''), 'Unknown'),
      nullif(rec->>'payback_months_min', '')::integer,
      nullif(rec->>'payback_months_max', '')::integer,
      coalesce(nullif(rec->>'interest_type', ''), 'Unknown'),
      coalesce(nullif(rec->>'repayment_frequency', ''), 'Unknown'),
      coalesce(rec->'exclusions', '[]'::jsonb),
      coalesce(rec->'required_documents', '[]'::jsonb),
      coalesce(nullif(rec->>'application_channel', ''), 'Unknown'),
      nullif(rec->>'application_url', ''),
      nullif(rec->>'contact_email', ''),
      nullif(rec->>'contact_phone', ''),
      coalesce(rec->'raw_text_snippets', '{}'::jsonb),
      coalesce(rec->'extraction_confidence', '{}'::jsonb),
      coalesce(rec->'related_documents', '[]'::jsonb),
      coalesce(rec->'notes', '[]'::jsonb)
    )
    on conflict (program_id) do update
    set
      program_name = excluded.program_name,
      funder_name = excluded.funder_name,
      site_adapter = excluded.site_adapter,
      page_type = excluded.page_type,
      parent_programme_name = excluded.parent_programme_name,
      source_url = excluded.source_url,
      source_urls = excluded.source_urls,
      source_domain = excluded.source_domain,
      source_page_title = excluded.source_page_title,
      scraped_at = excluded.scraped_at,
      raw_eligibility_data = excluded.raw_eligibility_data,
      funding_type = excluded.funding_type,
      funding_lines = excluded.funding_lines,
      ticket_min = excluded.ticket_min,
      ticket_max = excluded.ticket_max,
      currency = excluded.currency,
      program_budget_total = excluded.program_budget_total,
      deadline_type = excluded.deadline_type,
      deadline_date = excluded.deadline_date,
      funding_speed_days_min = excluded.funding_speed_days_min,
      funding_speed_days_max = excluded.funding_speed_days_max,
      geography_scope = excluded.geography_scope,
      provinces = excluded.provinces,
      municipalities = excluded.municipalities,
      postal_code_ranges = excluded.postal_code_ranges,
      industries = excluded.industries,
      use_of_funds = excluded.use_of_funds,
      business_stage_eligibility = excluded.business_stage_eligibility,
      turnover_min = excluded.turnover_min,
      turnover_max = excluded.turnover_max,
      years_in_business_min = excluded.years_in_business_min,
      years_in_business_max = excluded.years_in_business_max,
      employee_min = excluded.employee_min,
      employee_max = excluded.employee_max,
      ownership_targets = excluded.ownership_targets,
      entity_types_allowed = excluded.entity_types_allowed,
      certifications_required = excluded.certifications_required,
      security_required = excluded.security_required,
      equity_required = excluded.equity_required,
      payback_months_min = excluded.payback_months_min,
      payback_months_max = excluded.payback_months_max,
      interest_type = excluded.interest_type,
      repayment_frequency = excluded.repayment_frequency,
      exclusions = excluded.exclusions,
      required_documents = excluded.required_documents,
      application_channel = excluded.application_channel,
      application_url = excluded.application_url,
      contact_email = excluded.contact_email,
      contact_phone = excluded.contact_phone,
      raw_text_snippets = excluded.raw_text_snippets,
      extraction_confidence = excluded.extraction_confidence,
      related_documents = excluded.related_documents,
      notes = excluded.notes,
      updated_at = now();

    upserted_records := upserted_records + 1;
  end loop;

  for rec in
    select value
    from jsonb_array_elements(records)
    where coalesce(nullif(value->>'page_type', ''), '') = 'sub-product'
  loop
    resolved_parent_program_id := null;

    select fp.program_id
    into resolved_parent_program_id
    from public.funding_programmes fp
    where lower(coalesce(fp.program_name, '')) = lower(coalesce(nullif(rec->>'parent_programme_name', ''), ''))
      and lower(coalesce(fp.funder_name, '')) = lower(coalesce(nullif(rec->>'funder_name', ''), ''))
      and lower(coalesce(fp.source_domain, '')) = lower(coalesce(nullif(rec->>'source_domain', ''), ''))
    order by fp.scraped_at desc, fp.updated_at desc
    limit 1;

    if resolved_parent_program_id is null then
      insert into public.funding_programmes (
        program_id,
        program_name,
        funder_name,
        site_adapter,
        page_type,
        parent_programme_name,
        source_url,
        source_urls,
        source_domain,
        source_page_title,
        scraped_at,
        raw_eligibility_data,
        funding_type,
        funding_lines,
        ticket_min,
        ticket_max,
        currency,
        program_budget_total,
        deadline_type,
        deadline_date,
        funding_speed_days_min,
        funding_speed_days_max,
        geography_scope,
        provinces,
        municipalities,
        postal_code_ranges,
        industries,
        use_of_funds,
        business_stage_eligibility,
        turnover_min,
        turnover_max,
        years_in_business_min,
        years_in_business_max,
        employee_min,
        employee_max,
        ownership_targets,
        entity_types_allowed,
        certifications_required,
        security_required,
        equity_required,
        payback_months_min,
        payback_months_max,
        interest_type,
        repayment_frequency,
        exclusions,
        required_documents,
        application_channel,
        application_url,
        contact_email,
        contact_phone,
        raw_text_snippets,
        extraction_confidence,
        related_documents,
        notes
      )
      values (
        coalesce(rec->>'program_id', gen_random_uuid()::text),
        nullif(rec->>'program_name', ''),
        nullif(rec->>'funder_name', ''),
        nullif(rec->>'site_adapter', ''),
        nullif(rec->>'page_type', ''),
        nullif(rec->>'parent_programme_name', ''),
        rec->>'source_url',
        coalesce(rec->'source_urls', '[]'::jsonb),
        rec->>'source_domain',
        nullif(rec->>'source_page_title', ''),
        coalesce((rec->>'scraped_at')::timestamptz, now()),
        case when rec ? 'raw_eligibility_data' then rec->'raw_eligibility_data' else null end,
        coalesce(nullif(rec->>'funding_type', ''), 'Unknown'),
        coalesce(rec->'funding_lines', '[]'::jsonb),
        nullif(rec->>'ticket_min', '')::numeric,
        nullif(rec->>'ticket_max', '')::numeric,
        nullif(rec->>'currency', ''),
        nullif(rec->>'program_budget_total', '')::numeric,
        coalesce(nullif(rec->>'deadline_type', ''), 'Unknown'),
        nullif(rec->>'deadline_date', '')::date,
        nullif(rec->>'funding_speed_days_min', '')::integer,
        nullif(rec->>'funding_speed_days_max', '')::integer,
        coalesce(nullif(rec->>'geography_scope', ''), 'Unknown'),
        coalesce(rec->'provinces', '[]'::jsonb),
        coalesce(rec->'municipalities', '[]'::jsonb),
        coalesce(rec->'postal_code_ranges', '[]'::jsonb),
        coalesce(rec->'industries', '[]'::jsonb),
        coalesce(rec->'use_of_funds', '[]'::jsonb),
        coalesce(rec->'business_stage_eligibility', '[]'::jsonb),
        nullif(rec->>'turnover_min', '')::numeric,
        nullif(rec->>'turnover_max', '')::numeric,
        nullif(rec->>'years_in_business_min', '')::numeric,
        nullif(rec->>'years_in_business_max', '')::numeric,
        nullif(rec->>'employee_min', '')::integer,
        nullif(rec->>'employee_max', '')::integer,
        coalesce(rec->'ownership_targets', '[]'::jsonb),
        coalesce(rec->'entity_types_allowed', '[]'::jsonb),
        coalesce(rec->'certifications_required', '[]'::jsonb),
        coalesce(nullif(rec->>'security_required', ''), 'Unknown'),
        coalesce(nullif(rec->>'equity_required', ''), 'Unknown'),
        nullif(rec->>'payback_months_min', '')::integer,
        nullif(rec->>'payback_months_max', '')::integer,
        coalesce(nullif(rec->>'interest_type', ''), 'Unknown'),
        coalesce(nullif(rec->>'repayment_frequency', ''), 'Unknown'),
        coalesce(rec->'exclusions', '[]'::jsonb),
        coalesce(rec->'required_documents', '[]'::jsonb),
        coalesce(nullif(rec->>'application_channel', ''), 'Unknown'),
        nullif(rec->>'application_url', ''),
        nullif(rec->>'contact_email', ''),
        nullif(rec->>'contact_phone', ''),
        coalesce(rec->'raw_text_snippets', '{}'::jsonb),
        coalesce(rec->'extraction_confidence', '{}'::jsonb),
        coalesce(rec->'related_documents', '[]'::jsonb),
        coalesce(rec->'notes', '[]'::jsonb) || jsonb_build_array('Sub-funding parent could not be resolved during ingest.')
      )
      on conflict (program_id) do update
      set
        program_name = excluded.program_name,
        funder_name = excluded.funder_name,
        site_adapter = excluded.site_adapter,
        page_type = excluded.page_type,
        parent_programme_name = excluded.parent_programme_name,
        source_url = excluded.source_url,
        source_urls = excluded.source_urls,
        source_domain = excluded.source_domain,
        source_page_title = excluded.source_page_title,
        scraped_at = excluded.scraped_at,
        raw_eligibility_data = excluded.raw_eligibility_data,
        funding_type = excluded.funding_type,
        funding_lines = excluded.funding_lines,
        ticket_min = excluded.ticket_min,
        ticket_max = excluded.ticket_max,
        currency = excluded.currency,
        program_budget_total = excluded.program_budget_total,
        deadline_type = excluded.deadline_type,
        deadline_date = excluded.deadline_date,
        funding_speed_days_min = excluded.funding_speed_days_min,
        funding_speed_days_max = excluded.funding_speed_days_max,
        geography_scope = excluded.geography_scope,
        provinces = excluded.provinces,
        municipalities = excluded.municipalities,
        postal_code_ranges = excluded.postal_code_ranges,
        industries = excluded.industries,
        use_of_funds = excluded.use_of_funds,
        business_stage_eligibility = excluded.business_stage_eligibility,
        turnover_min = excluded.turnover_min,
        turnover_max = excluded.turnover_max,
        years_in_business_min = excluded.years_in_business_min,
        years_in_business_max = excluded.years_in_business_max,
        employee_min = excluded.employee_min,
        employee_max = excluded.employee_max,
        ownership_targets = excluded.ownership_targets,
        entity_types_allowed = excluded.entity_types_allowed,
        certifications_required = excluded.certifications_required,
        security_required = excluded.security_required,
        equity_required = excluded.equity_required,
        payback_months_min = excluded.payback_months_min,
        payback_months_max = excluded.payback_months_max,
        interest_type = excluded.interest_type,
        repayment_frequency = excluded.repayment_frequency,
        exclusions = excluded.exclusions,
        required_documents = excluded.required_documents,
        application_channel = excluded.application_channel,
        application_url = excluded.application_url,
        contact_email = excluded.contact_email,
        contact_phone = excluded.contact_phone,
        raw_text_snippets = excluded.raw_text_snippets,
        extraction_confidence = excluded.extraction_confidence,
        related_documents = excluded.related_documents,
        notes = excluded.notes,
        updated_at = now();

      upserted_records := upserted_records + 1;
    else
      insert into public.sub_funding_programmes (
        sub_program_id,
        parent_program_id,
        parent_program_name,
        sub_program_name,
        funder_name,
        site_adapter,
        page_type,
        source_url,
        source_urls,
        source_domain,
        source_page_title,
        scraped_at,
        raw_eligibility_data,
        funding_type,
        funding_lines,
        ticket_min,
        ticket_max,
        currency,
        program_budget_total,
        deadline_type,
        deadline_date,
        funding_speed_days_min,
        funding_speed_days_max,
        geography_scope,
        provinces,
        municipalities,
        postal_code_ranges,
        industries,
        use_of_funds,
        business_stage_eligibility,
        turnover_min,
        turnover_max,
        years_in_business_min,
        years_in_business_max,
        employee_min,
        employee_max,
        ownership_targets,
        entity_types_allowed,
        certifications_required,
        security_required,
        equity_required,
        payback_months_min,
        payback_months_max,
        interest_type,
        repayment_frequency,
        exclusions,
        required_documents,
        application_channel,
        application_url,
        contact_email,
        contact_phone,
        raw_text_snippets,
        extraction_confidence,
        related_documents,
        notes
      )
      values (
        coalesce(rec->>'program_id', gen_random_uuid()::text),
        resolved_parent_program_id,
        nullif(rec->>'parent_programme_name', ''),
        coalesce(nullif(rec->>'program_name', ''), nullif(rec->>'sub_program_name', '')),
        nullif(rec->>'funder_name', ''),
        nullif(rec->>'site_adapter', ''),
        coalesce(nullif(rec->>'page_type', ''), 'sub-product'),
        rec->>'source_url',
        coalesce(rec->'source_urls', '[]'::jsonb),
        rec->>'source_domain',
        nullif(rec->>'source_page_title', ''),
        coalesce((rec->>'scraped_at')::timestamptz, now()),
        case when rec ? 'raw_eligibility_data' then rec->'raw_eligibility_data' else null end,
        coalesce(nullif(rec->>'funding_type', ''), 'Unknown'),
        coalesce(rec->'funding_lines', '[]'::jsonb),
        nullif(rec->>'ticket_min', '')::numeric,
        nullif(rec->>'ticket_max', '')::numeric,
        nullif(rec->>'currency', ''),
        nullif(rec->>'program_budget_total', '')::numeric,
        coalesce(nullif(rec->>'deadline_type', ''), 'Unknown'),
        nullif(rec->>'deadline_date', '')::date,
        nullif(rec->>'funding_speed_days_min', '')::integer,
        nullif(rec->>'funding_speed_days_max', '')::integer,
        coalesce(nullif(rec->>'geography_scope', ''), 'Unknown'),
        coalesce(rec->'provinces', '[]'::jsonb),
        coalesce(rec->'municipalities', '[]'::jsonb),
        coalesce(rec->'postal_code_ranges', '[]'::jsonb),
        coalesce(rec->'industries', '[]'::jsonb),
        coalesce(rec->'use_of_funds', '[]'::jsonb),
        coalesce(rec->'business_stage_eligibility', '[]'::jsonb),
        nullif(rec->>'turnover_min', '')::numeric,
        nullif(rec->>'turnover_max', '')::numeric,
        nullif(rec->>'years_in_business_min', '')::numeric,
        nullif(rec->>'years_in_business_max', '')::numeric,
        nullif(rec->>'employee_min', '')::integer,
        nullif(rec->>'employee_max', '')::integer,
        coalesce(rec->'ownership_targets', '[]'::jsonb),
        coalesce(rec->'entity_types_allowed', '[]'::jsonb),
        coalesce(rec->'certifications_required', '[]'::jsonb),
        coalesce(nullif(rec->>'security_required', ''), 'Unknown'),
        coalesce(nullif(rec->>'equity_required', ''), 'Unknown'),
        nullif(rec->>'payback_months_min', '')::integer,
        nullif(rec->>'payback_months_max', '')::integer,
        coalesce(nullif(rec->>'interest_type', ''), 'Unknown'),
        coalesce(nullif(rec->>'repayment_frequency', ''), 'Unknown'),
        coalesce(rec->'exclusions', '[]'::jsonb),
        coalesce(rec->'required_documents', '[]'::jsonb),
        coalesce(nullif(rec->>'application_channel', ''), 'Unknown'),
        nullif(rec->>'application_url', ''),
        nullif(rec->>'contact_email', ''),
        nullif(rec->>'contact_phone', ''),
        coalesce(rec->'raw_text_snippets', '{}'::jsonb),
        coalesce(rec->'extraction_confidence', '{}'::jsonb),
        coalesce(rec->'related_documents', '[]'::jsonb),
        coalesce(rec->'notes', '[]'::jsonb)
      )
      on conflict (sub_program_id) do update
      set
        parent_program_id = excluded.parent_program_id,
        parent_program_name = excluded.parent_program_name,
        sub_program_name = excluded.sub_program_name,
        funder_name = excluded.funder_name,
        site_adapter = excluded.site_adapter,
        page_type = excluded.page_type,
        source_url = excluded.source_url,
        source_urls = excluded.source_urls,
        source_domain = excluded.source_domain,
        source_page_title = excluded.source_page_title,
        scraped_at = excluded.scraped_at,
        raw_eligibility_data = excluded.raw_eligibility_data,
        funding_type = excluded.funding_type,
        funding_lines = excluded.funding_lines,
        ticket_min = excluded.ticket_min,
        ticket_max = excluded.ticket_max,
        currency = excluded.currency,
        program_budget_total = excluded.program_budget_total,
        deadline_type = excluded.deadline_type,
        deadline_date = excluded.deadline_date,
        funding_speed_days_min = excluded.funding_speed_days_min,
        funding_speed_days_max = excluded.funding_speed_days_max,
        geography_scope = excluded.geography_scope,
        provinces = excluded.provinces,
        municipalities = excluded.municipalities,
        postal_code_ranges = excluded.postal_code_ranges,
        industries = excluded.industries,
        use_of_funds = excluded.use_of_funds,
        business_stage_eligibility = excluded.business_stage_eligibility,
        turnover_min = excluded.turnover_min,
        turnover_max = excluded.turnover_max,
        years_in_business_min = excluded.years_in_business_min,
        years_in_business_max = excluded.years_in_business_max,
        employee_min = excluded.employee_min,
        employee_max = excluded.employee_max,
        ownership_targets = excluded.ownership_targets,
        entity_types_allowed = excluded.entity_types_allowed,
        certifications_required = excluded.certifications_required,
        security_required = excluded.security_required,
        equity_required = excluded.equity_required,
        payback_months_min = excluded.payback_months_min,
        payback_months_max = excluded.payback_months_max,
        interest_type = excluded.interest_type,
        repayment_frequency = excluded.repayment_frequency,
        exclusions = excluded.exclusions,
        required_documents = excluded.required_documents,
        application_channel = excluded.application_channel,
        application_url = excluded.application_url,
        contact_email = excluded.contact_email,
        contact_phone = excluded.contact_phone,
        raw_text_snippets = excluded.raw_text_snippets,
        extraction_confidence = excluded.extraction_confidence,
        related_documents = excluded.related_documents,
        notes = excluded.notes,
        updated_at = now();

      delete from public.funding_programmes
      where program_id = coalesce(rec->>'program_id', '')
        and coalesce(page_type, '') = 'sub-product';

      upserted_sub_records := upserted_sub_records + 1;
    end if;
  end loop;

  if coalesce(jsonb_typeof(run_summary), '') = 'object' and coalesce(run_summary->>'run_id', '') <> '' then
    insert into public.scrape_runs (
      run_id,
      source_name,
      started_at,
      completed_at,
      status,
      seed_urls,
      total_urls_crawled,
      pages_fetched_successfully,
      pages_failed,
      programmes_extracted,
      programmes_after_dedupe,
      records_with_missing_program_name,
      records_with_missing_funder_name,
      records_with_unknown_funding_type,
      records_with_no_application_route,
      records_with_low_confidence_extraction,
      low_confidence_threshold,
      errors,
      warnings
    )
    values (
      run_summary->>'run_id',
      nullif(run_summary->>'source_name', ''),
      nullif(run_summary->>'started_at', '')::timestamptz,
      nullif(run_summary->>'completed_at', '')::timestamptz,
      coalesce(nullif(run_summary->>'status', ''), 'running'),
      coalesce(run_summary->'seed_urls', '[]'::jsonb),
      coalesce(nullif(run_summary->>'total_urls_crawled', '')::integer, 0),
      coalesce(nullif(run_summary->>'pages_fetched_successfully', '')::integer, 0),
      coalesce(nullif(run_summary->>'pages_failed', '')::integer, 0),
      coalesce(nullif(run_summary->>'programmes_extracted', '')::integer, 0),
      coalesce(nullif(run_summary->>'programmes_after_dedupe', '')::integer, 0),
      coalesce(nullif(run_summary->>'records_with_missing_program_name', '')::integer, 0),
      coalesce(nullif(run_summary->>'records_with_missing_funder_name', '')::integer, 0),
      coalesce(nullif(run_summary->>'records_with_unknown_funding_type', '')::integer, 0),
      coalesce(nullif(run_summary->>'records_with_no_application_route', '')::integer, 0),
      coalesce(nullif(run_summary->>'records_with_low_confidence_extraction', '')::integer, 0),
      nullif(run_summary->>'low_confidence_threshold', '')::numeric,
      coalesce(run_summary->'errors', '[]'::jsonb),
      coalesce(run_summary->'warnings', '[]'::jsonb)
    )
    on conflict (run_id) do update
    set
      source_name = excluded.source_name,
      started_at = excluded.started_at,
      completed_at = excluded.completed_at,
      status = excluded.status,
      seed_urls = excluded.seed_urls,
      total_urls_crawled = excluded.total_urls_crawled,
      pages_fetched_successfully = excluded.pages_fetched_successfully,
      pages_failed = excluded.pages_failed,
      programmes_extracted = excluded.programmes_extracted,
      programmes_after_dedupe = excluded.programmes_after_dedupe,
      records_with_missing_program_name = excluded.records_with_missing_program_name,
      records_with_missing_funder_name = excluded.records_with_missing_funder_name,
      records_with_unknown_funding_type = excluded.records_with_unknown_funding_type,
      records_with_no_application_route = excluded.records_with_no_application_route,
      records_with_low_confidence_extraction = excluded.records_with_low_confidence_extraction,
      low_confidence_threshold = excluded.low_confidence_threshold,
      errors = excluded.errors,
      warnings = excluded.warnings,
      updated_at = now();
  end if;

  return jsonb_build_object(
    'upserted_records', upserted_records,
    'upserted_sub_records', upserted_sub_records,
    'run_id', nullif(run_summary->>'run_id', ''),
    'rpc', 'ingest_funding_programmes'
  );
end;
$$;

revoke all on function public.ingest_funding_programmes(jsonb, jsonb) from public;
grant execute on function public.ingest_funding_programmes(jsonb, jsonb) to anon, authenticated, service_role;

commit;
